# Site settings
title: Kerrick's Homepage
email: kerrick@kerrickstaley.com
description: > # this means to ignore newlines until "baseurl:"
  Kerrick Staley's homepage. Under construction.
baseurl: ""
url: "http://www.kerrickstaley.com"
twitter_username: Kerksta
github_username:  kerrickstaley

# Build settings
markdown: kramdown
