# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Kerrick Staley
email: k@kerrickstaley.com
description: > # this means to ignore newlines until "baseurl:"
  Kerrick Staley's blog and homepage, serving up juicy posts about programming,
  Mandarin, learning (machine and human), and more!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.kerrickstaley.com" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:year/:month/:day/:title
github_username:  kerrickstaley
linkedin_username:  kerrick-staley

# Enable Google Analytics
google_analytics: UA-100131146-1

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

# Enable Disqus in Minima theme
disqus:
  shortname: kerrickstaley
